# A build specification (buildspec) file contains the collection of build commands
#   and related settings that AWS CodeBuild executes.
version: 0.2
phases:
  build:
    commands:
      - cd $WORKING_DIRECTORY
      - echo $BACKEND >> backend.tf.json
      - terraform init
      - |
        if [[ "$CONFIRM_DESTROY" == "0" ]]; then
          terraform apply -auto-approve
        else
          terraform destroy -auto-approve
        fi
